# Reference: https://dev.to/mattdark/using-docker-as-provider-for-vagrant-10me
FROM tony57/base:latest

RUN apt-get update -y && apt-get install -y --no-install-recommends ssh sudo openssh-client

#  Create a user named vagrant with password assigned, and grant it root privilege
RUN useradd --create-home -s /bin/bash vagrant
RUN (echo 'vagrant:vagrant' | chpasswd) && (echo 'vagrant ALL = NOPASSWD: ALL' > /etc/sudoers.d/vagrant)
RUN chmod 440 /etc/sudoers.d/vagrant

# ssh folder to store config
RUN mkdir -p /home/vagrant/.ssh
RUN chmod 700 /home/vagrant/.ssh

# Temprary key here, will be replaced after initialization
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==" > /home/vagrant/.ssh/authorized_keys
RUN chmod 600 /home/vagrant/.ssh/authorized_keys
RUN chown -R vagrant:vagrant /home/vagrant/.ssh

# ---- Not understand ----
RUN sed -i -e 's/Defaults.*requiretty/#&/' /etc/sudoers
RUN sed -i -e 's/\(UsePAM \)yes/\1 no/' /etc/ssh/sshd_config && mkdir /var/run/sshd
# ---- Not understand ----

# Installing dev tools
RUN apt-get -y install git vim curl

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
